### ISSUE TITLE
SYSTEM_ALERT_WINDOW

### ISSUE THREAD

**Issue by ray-pixar** [someshkumar049/PermissionMadeEasy#2]
hi.
please add support for `SYSTEM_ALERT_WINDOW`

**Comment by someshkumar049** [comment]
According to official docs of [SYSTEM_ALERT_WINDOW](https://developer.android.com/reference/android/Manifest.permission#SYSTEM_ALERT_WINDOW) we shouldn't ask for it instead we should redirect user to appropriate settings screen though intent. 

> Note: If the app targets API level 23 or higher, the app user must explicitly grant this permission to the app through a permission management screen. The app requests the user's approval by sending an intent with action Settings.ACTION_MANAGE_OVERLAY_PERMISSION

**Comment by someshkumar049** [comment]
I am closing this for now as this is not supposed to be in library. Please open a new issue if you think i'm wrong here.
